### ISSUE TITLE
Probe failed to find any functional HID backend

### ISSUE THREAD

**Issue by aydinhus** [abcminiuser/python-elgato-streamdeck#107]
Hi, I'm getting this error when i run Example Script: Device Information on m1 mac. hidapi already installed. Anyone have any ideas on this?

('Probe failed to find any functional HID backend.', {'libusb': TransportError("No suitable LibUSB HIDAPI library found on this system. Is the 'libhidapi.dylib' library installed?")})

**StreamDeck Information**
mk2

**System Information**

streamdeck in ./venv-test/lib/python3.8/site-packages (0.9.3)
macOS Monterey 12.5.1
hidapi 0.12.0 is already installed and up-to-date.

 Thanks

**Comment by abcminiuser** [comment]
Can you test the latest HEAD please? Either 6753750bf2487b029947f3d61a5c51a640210d7b or 99e32964237b4c559f83f4e34f3d9025647cf473 should address this, it is now able to find my installed library on a native M1 mac.

**Comment by aydinhus** [comment]
> Can you test the latest HEAD please? Either [6753750](https://github.com/abcminiuser/python-elgato-streamdeck/commit/6753750bf2487b029947f3d61a5c51a640210d7b) or [99e3296](https://github.com/abcminiuser/python-elgato-streamdeck/commit/99e32964237b4c559f83f4e34f3d9025647cf473) should address this, it is now able to find my installed library on a native M1 mac.

Same for [6753750]

`Exception has occurred: ProbeError
('Probe failed to find any functional HID backend.', {'libusb': TransportError("No suitable LibUSB HIDAPI library found on this system. Is the 'libhidapi.dylib' library installed?")})`

[99e3296]

`Exception has occurred: ProbeError
('Probe failed to find any functional HID backend.', {'libusb': UnboundLocalError("local variable 'homebrew_prefix' referenced before assignment")})
  File "/Users/_/Documents/test/elgato/deck.py", line 47, in <module>
    streamdecks = DeviceManager().enumerate()`

**Comment by aydinhus** [comment]
> Hrm. The second exception is my mistake - that means it can't find any Homebrew installation on your system.
> 
> What is the path to `libhidapi.dylib` on your system, and how did you install it?

via brew, `brew install hidapi`

/opt/homebrew/lib/libhidapi.dylib
/opt/homebrew/Cellar/hidapi/0.12.0/lib/libhidapi.dylib

I tried to hardcode `homebrew_prefix = "/opt/homebrew/"` and it worked, thanks for your help.

Found 1 Stream Deck(s).

Deck 0 - Stream Deck Original.
         - ID: DevSrvsID:...
         - Serial: '...'
         - Firmware Version: '1.01.000'
         - Key Count: 15 (in a 3x5 grid)
         - Key Images: 72x72 pixels, JPEG format, rotated 0 degrees, mirrored horizontally/vertically
