### ISSUE TITLE
Rounded corners not displayed correctly on Stream Deck XL

### ISSUE THREAD

**Issue by FroztOfficial** [abcminiuser/python-elgato-streamdeck#110]
# Info
* Stream Deck XL
* Arch Linux
* python-elgato-streamdeck version 0.9.3

# Bug
On the Stream Deck XL the images are displayed incorrectly. If you look closely on the following images you can see that on the `python-elgato-streamdeck` version, the corners are not rounded off, like it's on the `Official Stream Deck Software`.

## Official Stream Deck Software:
![1](https://user-images.githubusercontent.com/51519573/209473964-c345cd4f-3401-4410-9389-6a38e9178bef.png)

## python-elgato-streamdeck:
![2](https://user-images.githubusercontent.com/51519573/209473965-c209e8f6-98c1-48ee-a8c1-2987453f96b5.png)

**Comment by Core447** [comment]
I think this should not be implemented at the library level, but rather in the software that uses the library. Force-rounding all provided images will result in much lower performance when displaying videos or gifs on the deck.

**Comment by abcminiuser** [comment]
Agreed; it's up to the project using this library to style the buttons however they like. I don't think I should be enforcing a given style on everyone, as I've no idea what applications it'll be used in. If you want something like this, you'll need to mask out the corners of your key image with Pillow or something similar before applying it to a key.
