### ISSUE TITLE
Will StreamDeck Original V2 be added in any future?

### ISSUE THREAD

**Issue by ChutiReality** [abcminiuser/python-elgato-streamdeck#114]
I've been testing even basic usage examples and not everything works. For the moment the only thing was able to do was print out when a key is pressed and unpressed, retrieve the device name and few more details about it and change the brightness. When it comes to changing the image of a button, triggering callback functions, etc, nothing seems to work, and I'm using basic example usages you gave. Thanks for the work.

**Comment by abcminiuser** [comment]
This should already be supported in the latest library version; what library and OS version are you using?
