### ISSUE TITLE
OSX: sudo python3 example_deckinfo.py => OSError: open failed

### ISSUE THREAD

**Issue by uggel** [abcminiuser/python-elgato-streamdeck#12]
System Version: macOS 10.14.4 (18E226)
 Kernel Version: Darwin 18.5.0

```
$ sudo python3 example_deckinfo.py 
Found 1 Stream Deck(s).

Traceback (most recent call last):
  File "example_deckinfo.py", line 48, in <module>
    deck.open()
  File "/Users/arnold/projects/python-elgato-streamdeck/src/StreamDeck/Devices/StreamDeck.py", line 105, in open
    self.device.open()
  File "/Users/arnold/projects/python-elgato-streamdeck/src/StreamDeck/Transport/HIDAPI.py", line 51, in open
    self.hid.open_path(self.hid_info['path'])
  File "hid.pyx", line 72, in hid.device.open_path
OSError: open failed
```

I have not done the equivalent of setting up udev.
I had the same problem in linux and setting up the udev solved my issue there.

**Comment by abcminiuser** [comment]
MacOS is the one system I don't have or have any access to, so I can't debug this myself. Can you try printing out the device path, the value given to `open_path()` please? Perhaps it will shed some light on why the open is failing.

**Comment by dirkk0** [comment]
so possibly related to #3 ?
does a reboot help?

**Comment by louisiukas** [comment]
On a mac with same issue. Restart helped.
Running examples without `sudo` works.

**Comment by camdroid** [comment]
I'm having this same issue - restart didn't help, and I still get the same issue running as root or not. Here's the debugging output I've got so far:

```
[camdroid@camdroid-mbp streamdeck (master) (env)]$ python main.py
> /Users/camdroid/projects/streamdeck/env/lib/python3.6/site-packages/StreamDeck/Transport/HIDAPI.py(55)open()
-> print(e)
(Pdb) l
 50  	            """
 51  	            try:
 52  	                self.hid.open_path(self.hid_info['path'])
 53  	            except Exception as e:
 54  	                import pdb; pdb.set_trace()
 55  ->	                print(e)
 56
 57
 58
 59  	        def close(self):
 60  	            """
(Pdb) pp e
OSError('open failed',)
(Pdb) pp self.hid_info['path']
(b'IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/XHC1@14/XHC1@14000000'
 b'/HS08@14300000/USB2.0 Hub@14300000/AppleUSB20Hub@14300000/AppleUSB20HubPort@'
 b'14320000/USB 2.0 Hub@14320000/AppleUSB20Hub@14320000/AppleUSB20HubPort@14323'
 b'000/Stream Deck@14323000/IOUSBHostInterface@0/IOUSBHostHIDDevice@14323000,0')
(Pdb)
```

Looking at the output, potentially related to me having it plugged in through a USB hub (specifically [this one](https://www.amazon.com/MINIX-USB-C-Multiport-Adapter-HDMI/dp/B01N2LYC5P), which I've had some issues with before). Not really sure if that's relevant.

Happy to help debug more, would love to be able to get this working!

**Comment by camdroid** [comment]
Sorry, finally had the chance to test that out, and yep, it worked for me.

**Comment by abcminiuser** [comment]
New HID library backend integrated in aff0c2b905040cc841fdece10743eb853f09d6f7.

**Comment by hartmut-mariadb** [comment]
Had the same error on Linux. Checking the syslog messages generated when plugging in the Streamdeck device I noticed log entries about insufficient USB power available for the device.

 ```
Dec  8 10:18:37 hartmut-desktop kernel: [27485.800829] usb 1-5.3: New USB device found, idVendor=0fd9, idProduct=006d, bcdDevice= 2.00
Dec  8 10:18:37 hartmut-desktop kernel: [27485.800832] usb 1-5.3: New USB device strings: Mfr=1, Product=2, SerialNumber=3
Dec  8 10:18:37 hartmut-desktop kernel: [27485.800834] usb 1-5.3: Product: Stream Deck
Dec  8 10:18:37 hartmut-desktop kernel: [27485.800835] usb 1-5.3: Manufacturer: Elgato
Dec  8 10:18:37 hartmut-desktop kernel: [27485.800837] usb 1-5.3: SerialNumber: AL40I2C01722
Dec  8 10:18:37 hartmut-desktop kernel: [27485.800953] usb 1-5.3: rejected 1 configuration due to insufficient available bus power
Dec  8 10:18:37 hartmut-desktop kernel: [27485.800955] usb 1-5.3: no configuration chosen from 1 choice
```

Switching from the passive hub connector in my main keyboard to an active hub fixed that, and "streamdeck" now starts up properly :)
