### ISSUE TITLE
Missing Deck info in set_rotaryturn_callback

### ISSUE THREAD

**Issue by vectorcharlie** [abcminiuser/python-elgato-streamdeck#122]
**Describe the bug**
When calling set_rotaryturn_callback, only the value is sent to the function

**To Reproduce**
Set a call back for a StreamDeck Plus rotary and the funcion has to be only with one argument

deck.set_rotaryturn_callback(w.streamdeckRotaryTurned)

**StreamDeck Information**
StreamDeck Plus

Adding:

self.rotaryturn_callback(self, rotary_status)

to StreamDeck.py solves the issue.

**Comment by abcminiuser** [comment]
Not sure this is still relevant given the number of community patches for the StreamDeck +; I've just merged support into master based off one of them. Please re-open this issue if it is still present with the merged patch.
