### ISSUE TITLE
textsize removed in pillow > 10.0

### ISSUE THREAD

**Issue by ThibF** [abcminiuser/python-elgato-streamdeck#128]
**Describe the bug**
In pillow v10 and above, ImageDraw.textsize method is [removed](https://pillow.readthedocs.io/en/stable/releasenotes/10.0.0.html#fitsstubimageplugin) and to be replaced by [ImageDraw.textbbox()](https://pillow.readthedocs.io/en/stable/reference/ImageDraw.html#PIL.ImageDraw.ImageDraw.textbbox) and [ImageDraw.textlength()](https://pillow.readthedocs.io/en/stable/reference/ImageDraw.html#PIL.ImageDraw.ImageDraw.textlength)

**To Reproduce**
Update pillow or use Ubuntu 23.10 and start streamdeck.

it trigger this error message:

```
File "/usr/lib/python3/dist-packages/streamdeck_ui/api.py", line 341, in _render_key_image
    label_w, label_h = draw.textsize(text, font=true_font)
                       ^^^^^^^^^^^^^
AttributeError: 'ImageDraw' object has no attribute 'textsize'
```

**StreamDeck Information**
Not relevant

**System Information**
Ubuntu 23.10

**Comment by abcminiuser** [comment]
This appears to be a bug report for the downstream https://github.com/timothycrosley/streamdeck-ui/ project which uses this library. Can you please open an issue there?
