### ISSUE TITLE
New release that includes the added StreamDeck Plus support

### ISSUE THREAD

**Issue by ajbucci** [abcminiuser/python-elgato-streamdeck#131]
**Is your feature request related to a problem? Please describe.**
Would like to begin work on adding StreamDeck Plus support to [streamdeck-linux-gui](https://github.com/streamdeck-linux-gui/streamdeck-linux-gui) which is downstream of your awesome package! Having a new release will allow us to pin it in our dependencies.

**Describe the solution you'd like**
A new release that includes the already implemented StreamDeck Plus support.

Thank you!!

**Comment by abcminiuser** [comment]
Released as 0.9.5.
