### ISSUE TITLE
Stream Deck Neo Support 

### ISSUE THREAD

**Issue by dtcooper** [abcminiuser/python-elgato-streamdeck#140]
**Is your feature request related to a problem? Please describe.**

New product just announced, the Stream Deck Neo <https://www.elgato.com/us/en/p/stream-deck-neo>

**Describe the solution you'd like**

Support for the Neo in this library.

**Describe alternatives you've considered**

Initial support was committed in https://github.com/Julusian/node-elgato-stream-deck/commit/65197a7735d86ebd1883f96a5f7719b2bd1c95fb

**Additional context**

Cheers and thanks for the great library! :)

**Comment by AkechiShiro** [comment]
Any way to move this forward ? Is there any way we can help ?

**Comment by abcminiuser** [comment]
This is just a hobby project for me, and Elgato has made it clear that they are unwilling to sponsor the project - without access to hardware or protocol documentation I can't implement and test new device support.

Buying all the various StreamDeck models out of pocket is cost prohibitive, so unfortunately I'm reliant on the community at this point for testing and packet captures.

**Comment by Core447** [comment]
> Buying all the various StreamDeck models out of pocket is cost prohibitive, so unfortunately I'm reliant on the community at this point for testing and packet captures.

I can have a look at it, but I also don't have a Neo. Do you think the information from https://github.com/Julusian/node-elgato-stream-deck/commit/65197a7735d86ebd1883f96a5f7719b2bd1c95fb is sufficient?

**Comment by abcminiuser** [comment]
Yes, that's sufficient I think - looks like it's another StreamDeckOriginalV2 variant in terms of protcol, with a different USB product ID and key layout. Not hard to implement, but I don't want to do it blind and have complaints that it doesn't work when people test it on real hardware.

**Comment by AkechiShiro** [comment]
I do have one I may be able to do some tests

**Comment by xtheonexuk** [comment]
I just had my neo delivered yesterday so I'd be willing to help test / debug as required

**Comment by deechauhan** [comment]
Likewise, willing to help in testing/debug as well as just had my NEO delivered

**Comment by xtheonexuk** [comment]
@abcminiuser is there anything we can do to help you to work on this?

**Comment by Core447** [comment]
> I can have a look at it, but I also don't have a Neo. Do you think the information from [Julusian/node-elgato-stream-deck@65197a7](https://github.com/Julusian/node-elgato-stream-deck/commit/65197a7735d86ebd1883f96a5f7719b2bd1c95fb) is sufficient?

Small update: I haven't had the time for this yet, because I had to prioritize other things. I still want to check on it if I have more time, but if someone else is interested in adding support for it, please don't wait for me

**Comment by TheSchmidt** [comment]
BTW, the code for XL seems to work well with the Neo, therefore I have added pull request #147 to allow using it, at least the 8 main buttons.
Since I have no longer access to the Neo, I won't be able to help supporting the new touch buttons, or remove the redundant code.

**Comment by abowen** [comment]
> This is just a hobby project for me, and Elgato has made it clear that they are unwilling to sponsor the project - without access to hardware or protocol documentation I can't implement and test new device support.
> 
> Buying all the various StreamDeck models out of pocket is cost prohibitive, so unfortunately I'm reliant on the community at this point for testing and packet captures.

I'm in Newcastle. I can post you mine if you can make the time?

**Comment by VladFlorinIlie** [comment]
Hello everyone! I have added a new PR #151 to solve this issue. Let me know if it needs any more changes.

**Comment by abcminiuser** [comment]
Released in 0.9.6. Thanks everyone!
