### ISSUE TITLE
Timing information for Touch Events

### ISSUE THREAD

**Issue by devleaks** [abcminiuser/python-elgato-streamdeck#141]
Is it possible to "control" the timing that decides when a touch event type is a SHORT or LONG press?

Similarly, when a DRAG event occurs, is it possible to control the timing? It appears that the end of the DRAG is "forced" after some time, making long DRAGs impossible. Is this correct or am I missing something?

Thank you.

Best regards.

**Comment by Julusian** [comment]
Maintainer of the nodejs equivalent of this library here.
Last I checked (when the plus was new), the streamdeck just emits a 'short', 'long' or 'drag' event over usb, it doesn't provide anything else.
Unless something has changed in newer firmware, or someone has found a secret way of enabling extra events, I don't think anything is possible here

**Comment by Core447** [comment]
That's unfortunate

**Comment by devleaks** [comment]
So if I understand, Elgato "hardware" prevent access to button "release" information, correct? We only have touched SHORT, touched LONG (long being fixed by Elgato, with no mean to change it), and DRAG (for an arbitrary duration also, with no info on timing for press and release, only info on pixels positions).
If it is correct, I suppose we can close this enhancement request. Thank you.

**Comment by abcminiuser** [comment]
With the hardware protocol itself only giving the events are short/long/etc there's not much we can do unfortunately,
