### ISSUE TITLE
No function, Atribute error when i press a button

### ISSUE THREAD

**Issue by Michachacha** [abcminiuser/python-elgato-streamdeck#144]
**Describe the bug**
I can't select a button. When i try, i get the following message in the Terminal:

`
Traceback (most recent call last):
  File "/home/micha/.local/lib/python3.10/site-packages/streamdeck_ui/gui.py", line 523, in <lambda>
    button.clicked.connect(lambda button=button, buttons=buttons: button_clicked(ui, button, buttons))
  File "/home/micha/.local/lib/python3.10/site-packages/streamdeck_ui/gui.py", line 407, in button_clicked
    button_id = selected_button.index  # type: ignore # Index property added
AttributeError: 'bool' object has no attribute 'index'
Traceback (most recent call last):
  File "/home/micha/.local/lib/python3.10/site-packages/streamdeck_ui/gui.py", line 310, in change_page
    selected_button.setChecked(False)
AttributeError: 'bool' object has no attribute 'setChecked'
Traceback (most recent call last):
  File "/home/micha/.local/lib/python3.10/site-packages/streamdeck_ui/gui.py", line 310, in change_page
    selected_button.setChecked(False)
AttributeError: 'bool' object has no attribute 'setChecked'
`

**To Reproduce**
Start application, press any of the buttons (not the actual hardware buttons, i mean the software's representation of them)

**StreamDeck Information**
Streamdeck Mini

**System Information**
I installed using this guide: https://github.com/timothycrosley/streamdeck-ui/blob/master/docs/installation/ubuntu.md
AND when i got an error message after that, i installed libxcb-cursor0 because the error message asked for that.

Sorry, i'm a linux beginner.

System:
Linux Mint 21.3, Desktop: Xfce 4.18.1
Minix Z83-4

[code]
System:
  Kernel: 5.15.0-91-generic x86_64 bits: 64 compiler: gcc v: 11.4.0 Desktop: Xfce 4.18.1
    tk: Gtk 3.24.33 info: xfce4-panel wm: xfwm 4.18.0 vt: 7 dm: LightDM 1.30.0
    Distro: Linux Mint 21.3 Virginia base: Ubuntu 22.04 jammy
Machine:
  Type: Desktop System: MINIX product: Z83-4 v: V1.1 serial: <superuser required>
  Mobo: MINIX model: NEO Z83-4 v: V1.1 serial: <superuser required> UEFI: American Megatrends
    v: CHT0A150 date: 11/18/2016
Battery:
  Device-1: hidpp_battery_0 model: Logitech M350 Wireless Mouse serial: <filter>
    charge: 100% (should be ignored) rechargeable: yes status: Discharging
CPU:
  Info: quad core model: Intel Atom x5-Z8350 bits: 64 type: MCP smt: <unsupported> arch: Airmont
    rev: 4 cache: L1: 224 KiB L2: 2 MiB
  Speed (MHz): avg: 1680 min/max: 480/1920 cores: 1: 1680 2: 1680 3: 1680 4: 1680
    bogomips: 11520
  Flags: ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx
Graphics:
  Device-1: Intel Atom/Celeron/Pentium Processor x5-E8000/J3xxx/N3xxx Integrated Graphics
    driver: i915 v: kernel ports: active: HDMI-A-1 empty: DP-1,DP-2,HDMI-A-2 bus-ID: 00:02.0
    chip-ID: 8086:22b0 class-ID: 0300
  Display: x11 server: X.Org v: 1.21.1.4 compositor: xfwm v: 4.18.0 driver: X:
    loaded: modesetting unloaded: fbdev,vesa gpu: i915 display-ID: :0.0 screens: 1
  Screen-1: 0 s-res: 1920x1080 s-dpi: 96 s-size: 508x285mm (20.0x11.2") s-diag: 582mm (22.9")
  Monitor-1: HDMI-1 mapped: HDMI-A-1 model: Dell U2311H serial: <filter> res: 1920x1080 hz: 60
    dpi: 96 size: 509x286mm (20.0x11.3") diag: 584mm (23") modes: max: 1920x1080 min: 720x400
  OpenGL: renderer: Mesa Intel HD Graphics (CHV) v: 4.6 Mesa 23.0.4-0ubuntu1~22.04.1
    direct render: Yes
Audio:
  Device-1: Intel HDMI/DP LPE Audio driver: HdmiLpeAudio message: bus/chip ids unavailable
  Device-2: sof-bytcht rt5645 driver: SOF message: bus/chip ids unavailable
  Sound Server-1: ALSA v: k5.15.0-91-generic running: yes
  Sound Server-2: PulseAudio v: 15.99.1 running: yes
  Sound Server-3: PipeWire v: 0.3.48 running: yes
Network:
  Device-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet driver: r8169 v: kernel pcie:
    speed: 2.5 GT/s lanes: 1 port: e000 bus-ID: 01:00.0 chip-ID: 10ec:8168 class-ID: 0200
  IF: enp1s0 state: up speed: 1000 Mbps duplex: full mac: <filter>
Drives:
  Local Storage: total: 614.13 GiB used: 13.77 GiB (2.2%)
  ID-1: /dev/mmcblk0 vendor: Samsung model: BJNB4R size: 29.12 GiB type: SSD serial: <filter>
    rev: 0x8 scheme: GPT
  ID-2: /dev/mmcblk1 vendor: Samsung model: ED4QT size: 119.25 GiB type: SSD serial: <filter>
    scheme: MBR
  ID-3: /dev/sda type: USB vendor: Samsung model: Portable SSD T5 size: 465.76 GiB type: SSD
    serial: <filter> scheme: MBR
Partition:
  ID-1: / size: 28 GiB used: 13.77 GiB (49.2%) fs: ext4 dev: /dev/mmcblk0p2
  ID-2: /boot/efi size: 511 MiB used: 6.1 MiB (1.2%) fs: vfat dev: /dev/mmcblk0p1
Swap:
  ID-1: swap-1 type: file size: 1.33 GiB used: 109 MiB (8.0%) priority: -2 file: /swapfile
USB:
  Hub-1: 1-0:1 info: Hi-speed hub with single TT ports: 7 rev: 2.0 speed: 480 Mb/s
    chip-ID: 1d6b:0002 class-ID: 0900
  Device-1: 1-1:2 info: Samsung Portable SSD T5 type: Mass Storage driver: uas interfaces: 1
    rev: 2.1 speed: 480 Mb/s power: 500mA chip-ID: 04e8:61f5 class-ID: 0806 serial: <filter>
  Device-2: 1-2:3 info: Logitech Unifying Receiver type: Mouse,HID
    driver: logitech-djreceiver,usbhid interfaces: 2 rev: 2.0 speed: 12 Mb/s power: 98mA
    chip-ID: 046d:c52f class-ID: 0300
  Device-3: 1-3:4 info: Elgato Systems GmbH Stream Deck Mini type: HID driver: usbfs
    interfaces: 1 rev: 2.0 speed: 480 Mb/s power: 200mA chip-ID: 0fd9:0063 class-ID: 0300
    serial: <filter>
  Device-4: 1-4:5 info: Logitech Keyboard K120 type: Keyboard,HID driver: hid-generic,usbhid
    interfaces: 2 rev: 1.1 speed: 1.5 Mb/s power: 90mA chip-ID: 046d:c31c class-ID: 0300
  Hub-2: 2-0:1 info: Super-speed hub ports: 6 rev: 3.0 speed: 5 Gb/s chip-ID: 1d6b:0003
    class-ID: 0900
Sensors:
  System Temperatures: cpu: 54.9 C mobo: N/A
  Fan Speeds (RPM): N/A
Repos:
  Packages: 2205 apt: 2198 flatpak: 7
  No active apt repos in: /etc/apt/sources.list
  Active apt repos in: /etc/apt/sources.list.d/official-package-repositories.list
    1: deb http: //linux-mint.froonix.org virginia main upstream import backport
    2: deb http: //ftp-stud.hs-esslingen.de/ubuntu jammy main restricted universe multiverse
    3: deb http: //ftp-stud.hs-esslingen.de/ubuntu jammy-updates main restricted universe multiverse
    4: deb http: //ftp-stud.hs-esslingen.de/ubuntu jammy-backports main restricted universe multiverse
    5: deb http: //security.ubuntu.com/ubuntu/ jammy-security main restricted universe multiverse
Info:
  Processes: 262 Uptime: 19m wakeups: 6 Memory: 3.63 GiB used: 2.23 GiB (61.6%) Init: systemd
  v: 249 runlevel: 5 Compilers: gcc: 11.4.0 alt: 11/12 Client: Unknown python3.10 client
  inxi: 3.3.13
[/code]

**Comment by Michachacha** [comment]
Sorry, made a mistake posting this.

**Comment by Michachacha** [comment]
Sorry, made a mistake posting this.

**Comment by Core447** [comment]
> What was your fix for this? I've set everything up per the instructions (even did a full reinstall) and am getting the same error, except mine says "'bool' object has no attribute 'index'."

This seems to be a `streamdeck-linux-gui` problem. They have an old (closed) issue [here](https://github.com/streamdeck-linux-gui/streamdeck-linux-gui/pull/202).

**Comment by petrij98** [comment]
Interesting. Is there a suitable fix to deal with this for someone on Linux Mint 21.3? I can't select nor configure any of the buttons as a result of this bug. It just leaves my Stream Deck blank and unusable. I'd prefer to not go the manual installation and build from the repo, but if it's a last resort, it sounds like I'll only have so many other options.

**Comment by Core447** [comment]
In fact `streamcontroller-linux-gui` is in maintaining mode ([more infos](https://github.com/streamdeck-linux-gui/streamdeck-linux-gui/discussions/203)). The suggested alternative is [StreamController](https://flathub.org/apps/com.core447.StreamController) (I'm the developer of it 🙃).

If you have other questions about this, please comment [here](https://github.com/streamdeck-linux-gui/streamdeck-linux-gui) for `stream-deck-linux-gui` or [here](https://github.com/StreamController/StreamController) for StreamController (or join the [Discord](https://discord.gg/MSyHM8TN3u).

**Comment by petrij98** [comment]
Ah, I see. Very clever; lurking in the forums to lure people to try a better solution. I must say, it's very effective as is your software. lmao

**Comment by coolapso** [comment]
@petrij98 FYI  ... @Core447 and I are in sync and I was the one taking the initive to drive streamdeck-linux-gui users to his project as it is clearly supperior, and following much better software practices.  you can read more about it [here](https://github.com/streamdeck-linux-gui/streamdeck-linux-gui/discussions/203)
