### ISSUE TITLE
Stream Deck Mini low FPS

### ISSUE THREAD

**Issue by Aetherdyne** [abcminiuser/python-elgato-streamdeck#18]
New issue, as requested [here](https://github.com/abcminiuser/python-elgato-streamdeck/issues/13#issuecomment-531728315)

Animated example on my mini has a very low FPS, as shown in the animated example video [here](https://photos.google.com/share/AF1QipMZEQ5TS_Zt_VRl9enRO1Yo41WZlTiF9BdHScBGEvydHDH8jYrdQZOMWyt37p7Ypw/photo/AF1QipOeGYdWj9elnCBflaFTQ59erDbc02PMmtz-RMOd) or [in the album](https://photos.app.goo.gl/ReVH8MWnQhxjUmKJ7) if the first link doesn't work.

Python version: 3.7.2
Pillow version: 5.4.1
hidapi: 0.7.99.post21

Running on a Windows 7 machine with 8 GB and an AMD Phenom II X6 1100T Black.  (Yep, it's quite old.)

**Comment by abcminiuser** [comment]
Only your [previous gallery link](https://photos.google.com/share/AF1QipMZEQ5TS_Zt_VRl9enRO1Yo41WZlTiF9BdHScBGEvydHDH8jYrdQZOMWyt37p7Ypw?key=RE9Fc2FKa2wzcmhHamZRVEgtX2IxTFA3N0RYTWl3) works for me.

Those dependencies look normal -- but in the animated example when you press a button (to exit the demo) the Elgato logo is corrupted on the display. Looks like it's crashing/corrupting something inside the StreamDeck.

Does your system have multiple USB controllers on it (not ports, actual root hubs provided by different chips)? Might be worth trying other ports to see if this is a Windows HID driver issue with your USB chipset and the `hidapi` library. Also update your chipset drivers if possible.
