### ISSUE TITLE
debian - get_serial_number missing last digit

### ISSUE THREAD

**Issue by humbled** [abcminiuser/python-elgato-streamdeck#19]
debian buster (10)
Stream Deck Mini (2 of)
When executing get_serial_number, I get the first 11 digits of the serial only. When run previously on my Mac I would get all 12 digits.
Happy to provide more info

**Comment by humbled** [comment]
Running `lsusb` shows the full serial under each connected deck (as iSerial  3 BL36H....)

Installed python hidapi as HIDAPI backend

**Comment by abcminiuser** [comment]
Oops - I broke that in a recent refactoring; the original and mini variants share the same protocol, with minor subtle framing differences that tripped me up. Fixed in c1142c4f8dfad3b8e964fac80e8b416b43949c02.

**Comment by humbled** [comment]
Fixed, thanks.
Btw would be great if you tagged releases in github so we could see which pypi releases relate to which commits

**Comment by abcminiuser** [comment]
That's a good idea! I meant to do it when I stated the project, and plumb forgot. I've tagged off 0.5.0 and will do so for future releases.
