### ISSUE TITLE
.set_key_image() doesn't scale correctly on Stream Deck XL

### ISSUE THREAD

**Issue by PFython** [abcminiuser/python-elgato-streamdeck#20]
Hi - first of all amazing job with this library.  I haven't found anything to compare with it for Python and it's really opening some creative doors for us, thank you.

Small thing - I noticed that images don't scale correctly on our Stream Deck XL (4x8 buttons) though.  Please see attached images as example input and output:

Input
![globe portrait](https://user-images.githubusercontent.com/35893632/65922102-1835cc80-e3dc-11e9-9a22-823406ddbd4c.png)

Output
![20190930_233839](https://user-images.githubusercontent.com/35893632/65922054-f3415980-e3db-11e9-88fd-baa2568f1e71.jpg)

As you can see the image seems to be repeated on the deck itself, with the right hand image curiously a bit larger than the left hand one.

All the best,
Peter

**Comment by abcminiuser** [comment]
Thanks for the report! I've pushed a fix in 2ebbbf0f606ad7801bbb950663b03c34d0f831fb - I had the rows and columns count swapped on the StreamDeck XL, so it was resizing the image incorrectly. Could you please test and confirm that it solves the issue?

**Comment by PFython** [comment]
Bingo!  Works fine now thanks :)
