### ISSUE TITLE
New Original StreamDeck hardware variant unsupported

### ISSUE THREAD

**Issue by skandix** [abcminiuser/python-elgato-streamdeck#28]
When I do lsusb on my laptop with arch where I have my stream deck plugged into, I get a stream deck with this info ```Bus 001 Device 025: ID 0fd9:006d Elgato Systems GmbH USB2.0 Hub``` When I look into the code, the stream deck is supposed to have 0060 as a idProduct… so by this I'm curious if anyone else have experienced this. I've tried to edit the code so that it says 006d instead of 0060 with not much luck.

**Comment by abcminiuser** [comment]
What version of the Streamdeck is it? Are there any visible external USB ports on it?

**Comment by skandix** [comment]
It's the Streamdeck Original and there's no usb ports on it.

**Comment by abcminiuser** [comment]
That's highly unusual then. Does it work with the original software? Given the product ID and strings I'd suspect a manufacturing error, where they loaded in the wrong configuration data into the device. If it still works with the original software that would imply that there's enough of the wacky units out there that they had to put in a workaround for it.

**Comment by skandix** [comment]
I tried it with a mac i had lying around, and that software worked without problems. I did record the hid, and seems like it still have the same setup with the buttons and such, but that the id is diffrent on what its supposed to be is just strange, i couldn't find a valid fcc for it either so i migth/ going to spend some time looking into this in the christmas break of what can be done so that i can start working on the use cases i've had in mind.

**Comment by skandix** [comment]
https://github.com/Lange/node-elgato-stream-deck/issues/76
Aigth, new hardware revision from elgato, bitfocus is working on a fix for it.

https://github.com/bitfocus/companion/issues/886

**Comment by abcminiuser** [comment]
Dang. I've done some spelunking through the StreamDeck code in Ghidra and I see that the two models are supported, but they seem to use the same protocol code for writing to the keys. That doesn't mesh up with those links, where someone said it failed when they tried forcing the existing third party code to use it.

Just for kicks, can you try changing the value of `USB_PID_STREAMDECK_ORIGINAL` to `0x0060` and see if it works? I'm very interested in all the behaviors - what happens and is printed when you run `example_deckinfo.py`, and what happens when you run the `example_basic.py` script. Does anything work, like the key press reads or getting the serial number?

**Comment by abcminiuser** [comment]
I've updated my driver code to match what the real software is doing for sending images, where it uses an 8191 byte transfer of two pages, with the image data split equally between both pages. I've also patched in the new product ID, so the latest Git revision of the library should detect your device even if it doesn't work right yet.

**Comment by skandix** [comment]
I tried changing the ```USB_PID_STREAMDECK_ORIGINAL``` but didn't seem to do the trick. Will tryout the revision when I'm back home from traveling.

**Comment by abcminiuser** [comment]
I wouldn't think the other change I made will help either then, in that case. Knowing what parts work (key reading? Serial number reading?) would be helpful to know so I can concentrate on just the broken parts.

**Comment by skandix** [comment]
Ofcourse, will send that over when i get back can Even send over a hid recording from the device aswell by pushing the buttons

**Comment by skandix** [comment]
Model: 20GAA9902
Serial: AL40I2C01775

**Comment by skandix** [comment]
none of the examples truly "work", it feels like they connect to the streamdeck, but at the same time iit doesn't connec to the streamdeck

**Comment by WildEdric** [comment]
New to Companion having just bought a StreamDeck XL...and getting the message '16. 14:40:10 USB(undefined): Found device, but no access. Please quit any other applications using the device, and try again.'  Guessing this is the problem everyone is talking about..?  Or is it something else?

**Comment by abcminiuser** [comment]
Looks like the Gen2 original StreamDeck now has a protocol similar to the XL.

https://github.com/Lange/node-elgato-stream-deck/commit/c9357acefa85df5870288212e7d31d01b4b68688

**Comment by haakonnessjoen** [comment]
hehe, @abcminiuser, that update is by us, to add support for it in companion :) Support for the new device is fixed in 56c450c1a

**Comment by haakonnessjoen** [comment]
@abcminiuser, Yes, it is in fact exactly the same protocol as the XL, just that the images is still 72x72 as with the old hardware.

**Comment by abcminiuser** [comment]
Well that certainly makes things easier, thanks @haakonnessjoen!

Fixed in 605c68c7c9195fe35931035ad10b9e273943434a. I'm resisting the temptation to try to pull out the first/second generation protocols into base classes for now, as the gen 1 devices have slight variations so I wouldn't put it past future devices to deviate from the current V2 protocol as well.

@skandix could you please test the current master against your V2 Original StreamDeck and let me know if it works?

**Comment by haakonnessjoen** [comment]
Hi. I've tested it for you now. Ran the example_basic.py, and it worked both on new and old Stream Deck 15 buttons device :)

The version string is a bit weird though. Seems like the first byte is wrong, as it is like it sent 0x0D to the terminal:
```
Opened 'Stream Deck Original (V2)' device (serial number: '
                                                           XXXXXXXXXXXX')
```

This also happens on the XL. But this did not happen on the original stream deck v1, or the stream deck mini. There the serial number is on the same line.

**Comment by abcminiuser** [comment]
Thanks for testing! It's a pain not having my own device to try this out with, but if I had to buy all the Streamdeck variants that are out now I'd be flat broke. Perhaps when the inevitable Mini V2 comes out I'll get one of those for protocol testing as it will be more affordable.

The odd serial number is, well, odd. The report to get the serial number returns an array of bytes, with the first byte being the sent report ID, the next being a string length, then the actual bytes of the string. In my code, I skip over the first two bytes of the returned report array before trying to extract out the string, which should be correct.

A 0x0D or 0xC byte (the string length byte in the second returned byte of the report array) being interpreted as part of the string would explain what you are seeing -- but not why it's occurring.

Which of the two HID backends are you using, and on what OS platform? Can you try dumping out the raw data returned by `serial = self.device.read_feature(0x06, 32)` so I can take a look please?

**Comment by skandix** [comment]
Hi, haven't had time before now to try it, but it works flawlessly had to fiddle a little to get the correct driver for arch linux. Will try to sort out the correct ones I used to get it working properly, and make a pull request for it.. Now it was just about to see if I can make something cool with this.

**Comment by abcminiuser** [comment]
Thanks @skandix, @haakonnessjoen ! I've made a new 0.6.3 release with the latest fixes applied.

@haakonnessjoen let's move the troubleshooting of the XL and Original V2 serial numbers to a new issue please.
