### ISSUE TITLE
HID library cannot select which Linux backend is to be used if multiple are present

### ISSUE THREAD

**Issue by abcminiuser** [abcminiuser/python-elgato-streamdeck#29]
Documenting here so I don't forget.

Currently on Linux the `hid` wrapper Python library I use supports two possible low level HID backends, HIDAPI and libUSB. The former is incompatible with the Original StreamDeck as it has a fixed 4KB maximum report size compiled into it by default, while the Original needs around 8KB for image data. The libUSB backend works.

I've added an explicit blacklist in 88fbc5c5bfa313cf3cbbf4ef658b9b51b595d520 to ensure only the working backend is chosen by the HID library, but this forces the user to uninstall the HIDAPI backend that other applications might depend on.

A proper fix is to either patch the `hid` python library with a way to explicitly select which is to be used, or incorporate a HID wrapper into this library that only selects libUSB.

**Comment by humbled** [comment]
I switched from hidapi to hid in my pip requirements after reading the recommendation change in the README. 
On Linux (prod) I had to `apt-get install libhidapi-libusb0` for it to work. Seems `pip install hid` (inside virtualenv) wasn't sufficient to prevent `Probe failed to find any functional HID backend`.

On Mac (dev) I get same failure to find HID backend message. More reluctant to try things on this box without advice.

So 2 things:
1) `apt-get install libhidapi-libusb0` needs to be added to the README?
2) What's the approach to get a valid hid backend on Mac?

Thanks

**Comment by jsebean** [comment]
The problem with this patch is it breaks it on Arch. I was helping a friend with this as I do not have a streamdeck, but Arch packages both `libhidapi-hidraw.so` and `libhidapi-libusb.so` in a single package `hidapi`. Removing the system libraries (renaming) makes it work but that's a really ugly hack.
