### ISSUE TITLE
reboot

### ISSUE THREAD

**Issue by dirkk0** [abcminiuser/python-elgato-streamdeck#3]
Hi,

 thanks for the lib, works like a charm!

I needed to reboot my Pi, otherwise the streamdeck couldn't be accessed. I am pretty sure there is a better way to solve this, so I didn't create a pull request.

Cheers, Dirk

**Comment by abcminiuser** [comment]
Interesting. What OS are you running on it? I used the default latest Raspbian image form mid this year, according to the setup script I put in https://github.com/abcminiuser/python-elgato-streamdeck#raspberry-pi-installation and didn't run into this.

When it failed, what was the error? Did it only occur until the first reboot, and then worked from then on? If so, it might be the udev rule not being picked up by the system properly.

**Comment by dirkk0** [comment]
I think this Pi is on 2018-10-09-raspbian-stretch; I dont remember the exact error but I think it was that Deck.open failed. Yes, it occurred until the first reboot and was gone then.

**Comment by abcminiuser** [comment]
Ah, it'll be the `udev` rule not taking affect until the reboot. Apparently there's a (possibly distribution-specific) way to make it reload the updated rules and apply it to already connected devices, but I've just added a note in de76dd1502d2d944b2c9a6750ef9328ffc431eb8 for now to reboot after initial install.
