### ISSUE TITLE
Unable to start streamdeck after install

### ISSUE THREAD

**Issue by Noodles4Pasta** [abcminiuser/python-elgato-streamdeck#30]
After following all instructions to install this in POP_OS ( a fork of Ubuntu) and installing all dependencies as needed, the command "streamdeck" does not start the program. All I get is "command not found" in terminal.

I did get a warning that a file needed added to "PATH" and tried to do that, but could still never get "streamdeck" to work. Also there are no instructions or link to instructions on howw to add it to auto start as suggested...

I am stuck and dont know what to try next, as I am a new (ish) user on linux.

(now for the obligatory "dis is broke, fix nao") XD

any help would be greatly appreciated!

**Comment by abcminiuser** [comment]
Hi,

This is a python control library for the StreamDecks - not a replacement for the official software. You can use this library to make custom scripts or applications that control a StreamDeck. There's a few python examples included that show off the basics of the library; run `python3 src/example_basic.py` to see one of them running.

If you want a replacement for the official software, look at [this project by Timothy Crosley ](https://timothycrosley.com/project-7-streamdeck_ui) which uses this library but provides a GUI application to configure custom button actions.
