### ISSUE TITLE
Libraries for CentOS7.7

### ISSUE THREAD

**Issue by lee11lee** [abcminiuser/python-elgato-streamdeck#31]
Hi,

does anyone have the correct libraries needed for CentOS 7.7?
I’ve found a couple different one, but I’m not sure which one are correct..

Any help would be greatly appreciated.

lee

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by lee11lee** [comment]
I finally got it to work. For those having the same problem, here is my list of what to do:

intall hid:
pip3 install hid

Install HID library
yum install hidapi

Install libusb
yum install libusb

install libudev (systemd-devel)
yum install systemd-devel

4.6 Rules
sudo tee /etc/udev/rules.d/10-streamdeck.rules << EOF
SUBSYSTEMS=="usb", ATTRS{idVendor}=="0fd9", GROUP="users"
EOF

Add the udev rules using your favorite text editor:
sudo nano /etc/udev/rules.d/99-streamdeck.rules
SUBSYSTEM=="usb", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="0060", MODE:="666", GROUP="plugdev"
SUBSYSTEM=="usb", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="0063", MODE:="666", GROUP="plugdev"
SUBSYSTEM=="usb", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="006c", MODE:="666", GROUP="plugdev"
SUBSYSTEM=="usb", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="006d", MODE:="666", GROUP="plugdev"

reload rules
sudo udevadm control --reload-rules

Unplug und replug device

pip3 install --user streamdeck_ui

streamdeck

**Comment by abcminiuser** [comment]
Awesome! Closing for now - hopefully people can find this with a websearch if they have similar issues. If enough people are interested I can start trying to figure out how to restructure the documentation to include per-platform setup instructions.
