### ISSUE TITLE
OSX Catalina trouble with HID

### ISSUE THREAD

**Issue by wolfviking0** [abcminiuser/python-elgato-streamdeck#37]
Hi,

I am trying to use the library under my MBP running Catalina. But I am not able to run because of Exception from HID.
I am almost sure it's a security of Catalina who do not allow accessing the device. I try running the script with sudo but same issue.
I also convert my script to an executable app with pyinstaller, and try to force allowing access but still same issue.

Any suggestion how I can make the library working with Catalina?

Thanks

```
> python3 streamdecktest.py
Found 1 Stream Deck(s).
Device 0 : <StreamDeck.Devices.StreamDeckXL.StreamDeckXL object at 0x108daf690>
Traceback (most recent call last):
  File "streamdecktest.py", line 115, in <module>
    deck.open()
  File "/usr/local/lib/python3.7/site-packages/StreamDeck/Devices/StreamDeck.py", line 122, in open
    self.device.open()
  File "/usr/local/lib/python3.7/site-packages/StreamDeck/Transport/HID.py", line 48, in open
    self.hid = hid.Device(path=self.hid_info['path'])
  File "/usr/local/lib/python3.7/site-packages/hid/__init__.py", line 130, in __init__
    raise HIDException('unable to open device')
hid.HIDException: unable to open device
```

**Comment by abcminiuser** [comment]
Sorry - I don't currently have access to a Catalina machine. I just tried this quickly on the one MacOS device I have temporary access to (running Mojave) and it was able to access the device without any issues.

Does using `sudo` help?

**Comment by abcminiuser** [comment]
Tested working on a Catalina machine, without `sudo`. Please re-open if you are still encountering issues with the latest library version.
