### ISSUE TITLE
RPI: No HID Backend found

### ISSUE THREAD

**Issue by itchy2** [abcminiuser/python-elgato-streamdeck#40]
I followed the Raspberry Installation Manual:

```
pi@raspberrypi:~/Desktop/New folder $ python3 ./DeviceInformation.py3
Traceback (most recent call last):
  File "./DeviceInformation.py3", line 44, in <module>
    streamdecks = DeviceManager().enumerate()
  File "/home/pi/.local/lib/python3.7/site-packages/StreamDeck/DeviceManager.py", line 90, in __init__
    self.transport = self._get_transport(transport)
  File "/home/pi/.local/lib/python3.7/site-packages/StreamDeck/DeviceManager.py", line 82, in _get_transport
    raise ProbeError("Probe failed to find any functional HID backend.", probe_errors)
StreamDeck.DeviceManager.ProbeError: ('Probe failed to find any functional HID backend.', {'hid': OSError('The libhidapi-hidraw0 backend is currently blacklisted for StreamDeck devices.'), 'hidapi': TypeError("enumerate() got an unexpected keyword argument 'vendor_id'")})
```

**Comment by richrosa** [comment]
try this. 

sudo apt-get install libhidapi-libusb0

**Comment by abcminiuser** [comment]
Yes, as @richrosa says the `libhidapi-libusb0` backend is required on Linux.

**Comment by abcminiuser** [comment]
@itchy2 or @richrosa could you please test out [this work in progress branch](https://github.com/abcminiuser/python-elgato-streamdeck/tree/new_hid_transport) on your local systems, and report back? This replaces both the `HID` and `HIDAPI` backends with my own ctypes bindings to the `hidapi-libusb0` system library.

In theory this should work as well as the existing `hid` backend with the upside that I can debug it easier and force the correct system library to be chosen when both are available.
