### ISSUE TITLE
Possible to account for "bezels" between keys when tiling the image across entire Stream Deck?

### ISSUE THREAD

**Issue by espoelstra** [abcminiuser/python-elgato-streamdeck#43]
I was poking at the streamdeck_ui package but was looking for a little inspiration as to what was possible, so I came over here and found the example scripts, but when using the example_tileimage.py it becomes pretty evident when looking at the mini vs V2 vs XL that the bezels aren't accounted for. The human brain is actually wired to "fill in the gaps", so it would be much less jarring if it were possible to just drop xx number of pixels on the edges of each tile to make the image more seamless.

A really good example of this done well is in the StreamDeckSharp repo in their "video playback" example, your brain can pretty quickly get past the fact that the image is playing on a matrix of screens, much like when looking at a video wall at a conference or sporting event.

https://www.youtube.com/watch?v=tNwUG0sPmKw

**Comment by abcminiuser** [comment]
Sure, just needs a little more math. Fixed in 74ba67eb5006ca43e3bbb958defbacfa17d6d3fd. I've just eyeballed the key spacing - needs some fine tuning.
