### ISSUE TITLE
Set animated gif image?

### ISSUE THREAD

**Issue by johnofcamas** [abcminiuser/python-elgato-streamdeck#5]
Is it possible to set an animated gif as the image?

**Comment by abcminiuser** [comment]
Currently not inside the library I've written - but http://www.pythonware.com/media/data/pil-handbook.pdf seems to indicate that PIL will read an animated images and allow you to extract the frames, so you could set that up on a timer to send over the frames to the StreamDeck at a fixed interval.

**Comment by johnofcamas** [comment]
That's pretty clever..  I'll give it a shot.  Thanks.
