### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by richardhboyd** [abcminiuser/python-elgato-streamdeck#50]
I get an error: `UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte` when I try to run the example from the docs.

```text
(.env) 38f9d35bacfd:StreamDeck rhboyd$ python ./app/discover.py 
Found 1 Stream Deck(s).

Deck 0 - Stream Deck Original (V2).
	 - ID: b'IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/RP05@1C,4/IOPP/UPSB@0/IOPP/DSB1@1/IOPP/UPS0@0/IOPP/pci-bridge@1/IOPP/pci1b73,1100@0/AppleUSBXHCIFL1100@01000000/AppleUSB20XHCIPort@01100000/Stream Deck@01100000/IOUSBHostInterface@0/IOUSBHostHIDDevice@01100000,0'
	 - Serial: '
                    AL47I2C05642'
Traceback (most recent call last):
  File "./app/discover.py", line 52, in <module>
    print_deck_info(index, deck)
  File "./app/discover.py", line 30, in print_deck_info
    print("\t - Firmware Version: '{}'".format(deck.get_firmware_version()))
  File "/Users/rhboyd/dev/StreamDeck/.env/lib/python3.7/site-packages/StreamDeck/Devices/StreamDeckOriginalV2.py", line 151, in get_firmware_version
    return self._extract_string(version[6:])
  File "/Users/rhboyd/dev/StreamDeck/.env/lib/python3.7/site-packages/StreamDeck/Devices/StreamDeck.py", line 100, in _extract_string
    return data.decode("utf-8").rstrip('\0')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
```

Changing [this line](https://github.com/abcminiuser/python-elgato-streamdeck/blob/master/src/StreamDeck/Devices/StreamDeck.py#L98) to

```python
return str(bytes(data), 'utf-8', 'ignore').rstrip(' \0')
```

ignores decode errors and *appears* to work correctly. Is this something I should submit a PR for or am I just being dumb?

```text
(.env) 38f9d35bacfd:StreamDeck rhboyd$ python ./app/discover.py 
Found 1 Stream Deck(s).

Deck 0 - Stream Deck Original (V2).
	 - ID: b'IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/RP05@1C,4/IOPP/UPSB@0/IOPP/DSB1@1/IOPP/UPS0@0/IOPP/pci-bridge@1/IOPP/pci1b73,1100@0/AppleUSBXHCIFL1100@01000000/AppleUSB20XHCIPort@01100000/Stream Deck@01100000/IOUSBHostInterface@0/IOUSBHostHIDDevice@01100000,0'
	 - Serial: '
                    AL47I2C05642'
	 - Firmware Version: '1.02.004'
	 - Key Count: 15 (3x5 grid)
	 - Key Images: 72x72 pixels, JPEG format, rotated 0 degrees, mirrored horizontally/vertically
```

Using Python3.7 on MacOS Mojave

**Comment by abcminiuser** [comment]
Interesting - a 0x80 byte is indeed not valid UTF-8. Ignoring it is certainly one way to deal with it, but it hints that I haven't got the starting offset right when extracting out the serial number string. The serials should essentiall be ASCII, but 0x80 maps to € in ASCII which isn't valid either.

The extra vertical newline in your output also suggests that there's at least one more junk byte other than the 0x80 at the start corrupting the output.

Would you be able to print out the raw bytes passed into `_extract_string()` please?

**Comment by richardhboyd** [comment]
I added a `print(data)` statement immediately before the return statement and here is the result.
```text
Deck 0 - Stream Deck Original (V2).
	 - ID: b'IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/RP05@1C,4/IOPP/UPSB@0/IOPP/DSB1@1/IOPP/UPS0@0/IOPP/pci-bridge@1/IOPP/pci1b73,1100@0/AppleUSBXHCIFL1100@01000000/AppleUSB20XHCIPort@01100000/Stream Deck@01100000/IOUSBHostInterface@0/IOUSBHostHIDDevice@01100000,0'
bytearray(b'\x0cAL47I2C05642\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00')
	 - Serial: '
                    AL47I2C05642'
bytearray(b'\x801.02.004\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00')
Traceback (most recent call last):
  File "app/discover.py", line 51, in <module>
    print_deck_info(index, deck)
  File "app/discover.py", line 29, in print_deck_info
    print("\t - Firmware Version: '{}'".format(deck.get_firmware_version()))
  File "/Users/rhboyd/dev/StreamDeck/.env/lib/python3.7/site-packages/StreamDeck/Devices/StreamDeckOriginalV2.py", line 151, in get_firmware_version
    return self._extract_string(version[6:])
  File "/Users/rhboyd/dev/StreamDeck/.env/lib/python3.7/site-packages/StreamDeck/Devices/StreamDeck.py", line 99, in _extract_string
    return str(bytes(data), 'utf-8').rstrip(' \0')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
```

using the change you made over the weekend also fixes the bug (though the newline is still there for some reason).

Here's the output with the ascii decode

```text
(.env) 38f9d35bacfd:StreamDeck rhboyd$ python app/discover.py 
Found 1 Stream Deck(s).

Deck 0 - Stream Deck Original (V2).
	 - ID: b'IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/RP05@1C,4/IOPP/UPSB@0/IOPP/DSB1@1/IOPP/UPS0@0/IOPP/pci-bridge@1/IOPP/pci1b73,1100@0/AppleUSBXHCIFL1100@01000000/AppleUSB20XHCIPort@01100000/Stream Deck@01100000/IOUSBHostInterface@0/IOUSBHostHIDDevice@01100000,0'
	 - Serial: '
                    AL47I2C05642'
	 - Firmware Version: '�1.02.004'
	 - Key Count: 15 (3x5 grid)
	 - Key Images: 72x72 pixels, JPEG format, rotated 0 degrees, mirrored horizontally/vertically
```

Given your fix, I'm happy to mark this as closed and create a feature request to figure out why that � is being introduced

**Comment by abcminiuser** [comment]
This is damned confusing - there's obviously an off-by-one in both cases, but the official app reads from the same starting indexes as I do as far as I can tell.

For the serial number it reads report ID 0x06 and extracts out the returned string from offset 2. For the firmware version it reads report ID 0x05 and extracts out the returned string from offset 6.

I can believe that they have their own off-by-one that's masked by their Unicode decode function throwing out the invalid starting byte, but the surely someone's noticed the unexpected newline (0x0C) character in the firmware version by now.

**Comment by abcminiuser** [comment]
Any chance you can tell me what version of HIDAPI you are using? [This might be related.](https://github.com/libusb/hidapi/commit/d8336833fc16df10275d24a0b51a33c5a2a91e6e#diff-5cbb2d1918d13a205b0b45fa24166f42)

**Comment by abcminiuser** [comment]
Added a workaround in c047eb7c2929cd92e1f316b54516588154b6f808 - although it looks like there's a cornucopia of fun bugs like this in HIDAPI depending on the version used and platform. There's no way to get the installed version from the HIDAPI API functions, so I just have to rely on terrible hacks.

Perhaps I'll need to look at figuring out how to build and package up a specific HIDAPI version as part of the library.
