### ISSUE TITLE
TransportError

### ISSUE THREAD

**Issue by jbonde** [abcminiuser/python-elgato-streamdeck#52]
I'm getting this error after Version 0.8.2 install: "StreamDeck.Transport.Transport.TransportError: Could not open HID device"
Used to work fine so wonder if it has anything to do with the latest update and the "Updated LibUSB transport backend so that device paths are returned as UTF-8 strings, not raw bytes"?

**Comment by abcminiuser** [comment]
What platform and version (E.g. Windows 10, 2004 or MacOS Mojave) are you using?

**Comment by jbonde** [comment]
Hardware	: BCM2711
Revision	:        b03111
Serial		: 100000006d263ff1
Model		: Raspberry Pi 4 Model B Rev 1.1

PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian

full error message:

Found 1 Stream Deck(s).

Traceback (most recent call last):
  File "/home/pi/tp/tp2.py", line 774, in <module>
    deck.open()
  File "/home/pi/.local/lib/python3.7/site-packages/StreamDeck/Devices/StreamDeck.py", line 148, in open
    self.device.open()
  File "/home/pi/.local/lib/python3.7/site-packages/StreamDeck/Transport/LibUSBHIDAPI.py", line 343, in open
    self.device_handle = self.hidapi.open_device(self.device_info['path'])
  File "/home/pi/.local/lib/python3.7/site-packages/StreamDeck/Transport/LibUSBHIDAPI.py", line 181, in open_device
    raise TransportError("Could not open HID device.")
StreamDeck.Transport.Transport.TransportError: Could not open HID device.

**Comment by abcminiuser** [comment]
I've just tried my own RPi4 running Raspbian Buster, with the same Python version. Apart from some missing dependencies in the documentation, it all worked smoothly.

Are you perhaps missing the udev rules to give your user account access to the device without super-user privileges? Without the udev rule loaded, the device will not be usable by a regular account, and attempting to open it will generate that message.

**Comment by jbonde** [comment]
That might well be the case as I had difficulties running this part according to your instructions. Copying the following code and executing from command prompt doesn't look right. I also tried to create a file with the EOF content in but with no luck. Is there a better way to handle udev?:

sudo tee /etc/udev/rules.d/10-streamdeck.rules << EOF
    SUBSYSTEMS=="usb", ATTRS{idVendor}=="0fd9", GROUP="users"
    EOF

**Comment by abcminiuser** [comment]
All that command is doing is creating a file `/etc/udev/rules.d/10-streamdeck.rules` as `root`, which contains the literal text:
```SUBSYSTEMS=="usb", ATTRS{idVendor}=="0fd9", GROUP="users"```. If you're having trouble, you could create that file and contents manually with something like `sudo nano /etc/udev/rules.d/10-streamdeck.rules` and pasting in the contents.

Once you've saved the file, unplug and re-plug the StreamDeck to ensure the rules are applied correctly.

**Comment by jbonde** [comment]
Makes sense. Updated the file and now it works with my Python application. Thanks for your support!

**Comment by abcminiuser** [comment]
No problem, glad you're all sorted!
