### ISSUE TITLE
StreamDeckXL.get_serial_number sometimes returning wrong results

### ISSUE THREAD

**Issue by theslimshaney** [abcminiuser/python-elgato-streamdeck#53]
**Description**
Normally, `self.device.read_feature(0x06, 32)` will return 
```
b'\x06\x0cAAAAAAAAAAAA\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
```

But sometimes, it will return 
```
b'\x06\x0cAAAAAAAAAAAA\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01'
```

I'm not sure exactly what causes to get into this 'sometimes \x01' state, but I have noticed it a few times after fiddling around with things. Maybe an improper abort is causing it? I can try to find out but will have to see.

I just recently started using this program, so I can't speak to any prior behavior. But I check a recent commit 1 month ago, before it would be returning 
```
b'\x06\x0cAAAAAAAAAAAA\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
```
But due to https://github.com/abcminiuser/python-elgato-streamdeck/commit/c047eb7c2929cd92e1f316b54516588154b6f808#diff-8fce19ef15b0c8c1aa404b2a80f62eecR237-R238, we're now sometimes getting this extra `\x01` byte at the end, which is breaking normal behavior of 
https://github.com/abcminiuser/python-elgato-streamdeck/blob/086691d40c858ee042ccf7cb3bfc8beea780be4e/src/StreamDeck/Devices/StreamDeckXL.py#L133-L142
https://github.com/abcminiuser/python-elgato-streamdeck/blob/086691d40c858ee042ccf7cb3bfc8beea780be4e/src/StreamDeck/Devices/StreamDeck.py#L92-L98

**To Reproduce**
I don't know exactly how to get the device into the state so that it returns the `\x01` byte at the end, but don't think that's too important for this issue.

**Possible fix**
I'm not familiar with device APIs like this at all, so just guessing here, but adding a check to see if the last byte is \x01 fixes the issue for me. But I'm not sure if it's ever okay for this byte to be \x01, so maybe since the comment only mentions Mac, there could be an OS check here. Or we should check for a long sequence of `'x00\x00\...\x01'` to remove possible false positive? Other ideas is maybe the `read_feature()` call or `_extract_string` function can be adjusted in StreamDeckXL.
I will make a PR for option 1 in case that solution is fine. But let me know if you want it tweaked, otherwise I will just leave it up you.

**StreamDeck Information**
StreamDeckXL

**System Information**
Linux, hidapi 0.9.0-2, python-elgato-streamdeck 0.8.2
I also have this plugged into a KVM switch USB hub, in case that's relevant.

**Comment by abcminiuser** [comment]
Would you mind re-testing bd1640316c70b652495693a63d69ace32a06ce4f on Linux please? I've changed the transport code to also only issue a larger-than-expected read request on Mac systems.
