### ISSUE TITLE
Windows 10 hidapi.dll Error

### ISSUE THREAD

**Issue by rayworrell** [abcminiuser/python-elgato-streamdeck#56]
This is definitely not a bug.  I'm sure it's all due to my ignorance, and I appreciate any help you can provide.  I'm anxious to use this library!

I downloaded the hidapi.dll and hidapi.lib from the libUSB GitHub project as directed.  Not knowing where the process would look, I placed these files into c:\Windows\System32, into the Python executable directory, and the directory of where my script resides.  However, I keep getting the error...

StreamDeck.DeviceManager.ProbeError: ('Probe failed to find any functional HID backend.', {'libusb': TransportError("No suitable LibUSB HIDAPI library found on this system. Is the 'hidapi.dll' library installed?",)})

Can you point me in the right direction?  I'm on a Windows 10 box.

Thanks,
Ray.

**Comment by yschroeder** [comment]
I just ran into this as well, but figured it out:

* Make sure to place both files into the correct Python folder e.g. `C:\Users\<username>\AppData\Local\Programs\Python\Python36-32` right next to the `python.exe`
* Use to correct version: Although my Win10 is x64, I had to use the x86 files compiled versions (but this my be due to my ancient python version)

**Comment by rayworrell** [comment]
> I just ran into this as well, but figured it out:
> 
> * Make sure to place both files into the correct Python folder e.g. `C:\Users\<username>\AppData\Local\Programs\Python\Python36-32` right next to the `python.exe`
> * Use to correct version: Although my Win10 is x64, I had to use the x86 versions (but this my be due to my ancient python version)

Thank you so much for responding!  You solved my issue!  I had the files in the right place.  I just had the wrong files there.  It was an x86 vs. x64 issue.  Bless you, man!

**Comment by abcminiuser** [comment]
Whoops, sorry, I missed this one. I'll add @yschroeder's instructions to the documentation.
