### ISSUE TITLE
Library doesn't work in Python 3.8 or 3.9 on Windows

### ISSUE THREAD

**Issue by vlaplante** [abcminiuser/python-elgato-streamdeck#57]
**Describe the bug**
When trying to use the library on Windows 10 using either Python 3.8 or 3.9, the library raises an exception when trying to enumerate the Stream Decks attached to the computer. The exception raised is 'ProbeError' and the message is ''Probe failed to find any functional HID backend.'

The hidapi.dll and hidapi.lib files are installed in the same directory as python.exe. The version of Python in both cases is the 32 bit version. With the same setup in Python 3.7, the example scripts run correctly.

**To Reproduce**
Install the 32 bit version of either Python 3.8 or 3.9. Download (or build) the hidapi.dll and hidapi.lib files and place them in the same directory as the python.exe. Run the example scripts provided in the source tree for python-elgato-streamdeck.

**StreamDeck Information**
The StreamDeck version is the StreamDeck XL.

**System Information**
Window 10, Build 2004, Ryzen 7 2700X, 3.70 GHz

Library version 0.8.2

**Comment by abcminiuser** [comment]
If you are using the 32-bit version of Python, are you copying over the matching x86 (not x64) HIDAPI DLL?

I use the 64-bit Python 3.8.2 locally on my Win10 system with no issues, against the HIDAPI 0.9.0's 64-bit prebuilt DLL.
