### ISSUE TITLE
Reading 32 bytes instead of 17 on StreamDeckXL for Serial Number

### ISSUE THREAD

**Issue by Saruspete** [abcminiuser/python-elgato-streamdeck#58]
**Describe the bug**
In `Devices/StreamDeckXL.py` the serial number is read over 32 bytes. On my system, it reports bad chars containing \0 (not stripped, because of a \1 at the rightmost position).:

```
(Pdb) p serial
b'\x06\x0cCL35J1A01471\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01'


(Pdb) p serial
b'\x06\x0cCL35J1A01471\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01'
(Pdb) s
--Call--
> /home/adrien/.cache/pypoetry/virtualenvs/streamdeck-ui-68pX5nCk-py3.7/lib/python3.7/site-packages/StreamDeck/Devices/StreamDeck.py(92)_extract_string()
-> def _extract_string(self, data):
(Pdb) s
> /home/adrien/.cache/pypoetry/virtualenvs/streamdeck-ui-68pX5nCk-py3.7/lib/python3.7/site-packages/StreamDeck/Devices/StreamDeck.py(98)_extract_string()
-> return str(bytes(data), 'ascii', 'replace').rstrip(' \0')
(Pdb) s
--Return--
> /home/adrien/.cache/pypoetry/virtualenvs/streamdeck-ui-68pX5nCk-py3.7/lib/python3.7/site-packages/StreamDeck/Devices/StreamDeck.py(98)_extract_string()->'CL35J1A01471...0\x00\x00\x01'
```

As other libraries are reading 17 bytes instead of 32, I guess there's an overflow there:

```
$ grep 'serial =' StreamDeck/Devices/StreamDeck*.py
StreamDeck/Devices/StreamDeckMini.py:        serial = self.device.read_feature(0x03, 17)
StreamDeck/Devices/StreamDeckOriginal.py:        serial = self.device.read_feature(0x03, 17)
StreamDeck/Devices/StreamDeckOriginalV2.py:        serial = self.device.read_feature(0x06, 32)
StreamDeck/Devices/StreamDeckXL.py:        serial = self.device.read_feature(0x06, 32)
```

**To Reproduce**
Show raw output of `serial = self.device.read_feature(0x06, 32)`

**StreamDeck Information**
StreamDeckXL

**System Information**
UI from Streamdeck_ui, streamdeck library v0.8.2

**Comment by abcminiuser** [comment]
Thanks for the report. I realized I can strip the strings better by just tossing all bytes past the first embedded NUL. That should fix all the cases where there's junk being returned by the device or by the kernel's HID driver when doing a feature report read.

Should be resolve in 5bcb1edcd80a5a7257de5aba3dadf2322bc27fb7 - if not please re-open.
