### ISSUE TITLE
Unable to open HID device

### ISSUE THREAD

**Issue by cmccandless** [abcminiuser/python-elgato-streamdeck#63]
**Describe the bug**
Unable to open HID device. I followed the libhidapi-libusb0 setup [here](https://python-elgato-streamdeck.readthedocs.io/en/stable/pages/backend_libusb_hidapi.html#linux-ubuntu-debian), but when I run `src/example_basic.py`, I see this:

```Bash
Found 1 Stream Deck(s).

Traceback (most recent call last):
  File "/home/cmccandless/repos/sandbox/python-elgato-streamdeck/src/example_basic.py", line 113, in <module>
    deck.open()
  File "/home/cmccandless/repos/sandbox/python-elgato-streamdeck/src/StreamDeck/Devices/StreamDeck.py", line 148, in open
    self.device.open()
  File "/home/cmccandless/repos/sandbox/python-elgato-streamdeck/src/StreamDeck/Transport/LibUSBHIDAPI.py", line 348, in open
    self.device_handle = self.hidapi.open_device(self.device_info['path'])
  File "/home/cmccandless/repos/sandbox/python-elgato-streamdeck/src/StreamDeck/Transport/LibUSBHIDAPI.py", line 181, in open_device
    raise TransportError("Could not open HID device.")
StreamDeck.Transport.Transport.TransportError: Could not open HID device.
```

**To Reproduce**
Follow all installation steps, the run `python3 src/example_basic.py`

**StreamDeck Information**
StreamDeck v2 (15 keys)

**System Information**
Ubuntu 20.04
Linux 5.4.0-65-generic #73-Ubuntu SMP Mon Jan 18 17:25:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

I'm using the latest from Github (f48a4012cf48ce4f64b2c576e892a6bcd5c6f185)

**Comment by Xlaits** [comment]
Are you doing this as root? Your user needs to have access to the device, as described [here](https://timothycrosley.github.io/streamdeck-ui/). Scroll down to the setup.

**Comment by abcminiuser** [comment]
Root access *shouldn't* be required, as the `udev` rules should assign the current user read/write permissions on the USB device. I did a documentation update to the rules in a49ce2cf33499523307e594b73faaac613e865c8 after feedback from users, adding the new `uaccess` tag to fix the permissions on non-Debian distributions.

**Comment by cmccandless** [comment]
Additional info: after posting this issue, I stumbled onto the Streamdeck UI project. That application works fine. I followed the ["Manual Installation" steps](https://timothycrosley.github.io/streamdeck-ui/#linux-quick-start). I will test to see if I can still reproduce the issue.

Possible causes:
- User was not part of `plugdev` group
- Streamdeck UI setup lists more udev rule entries (4) than the setup instructions I listed above (1). One or more of these missing may have caused my issue.

**Comment by cmccandless** [comment]
Unable to reproduce after Streamdeck UI installation. Suggest reviewing installation docs regarding user group membership and udev rules.

**Comment by cmccandless** [comment]
It's possible that the changes in https://github.com/abcminiuser/python-elgato-streamdeck/commit/a49ce2cf33499523307e594b73faaac613e865c8 are sufficient. When will that change to the docs populate to https://python-elgato-streamdeck.readthedocs.io/en/stable/pages/backend_libusb_hidapi.html#linux-ubuntu-debian?

**Comment by abcminiuser** [comment]
Oops - the documentation for `stable` is up to date now. Apparently something had gotten stuck for that build environment on ReadTheDocs, I had to wipe it for it to rebuild correctly.
