### ISSUE TITLE
PILHelper has no attribute 'create_scaled_image'

### ISSUE THREAD

**Issue by Xlaits** [abcminiuser/python-elgato-streamdeck#64]
**Describe the bug**
AttributeError: module 'StreamDeck.ImageHelpers.PILHelper' has no attribute 'create_scaled_image'

```Traceback (most recent call last):
  File "/home/xlaits/Documents/Programming/Python/Streamdeck/Streamdeck.py", line 102, in <module>
    create_animation_frames(deck, "Legion-StreamDeckIcon-Firefox-256x256.gif"),
  File "/home/xlaits/Documents/Programming/Python/Streamdeck/Streamdeck.py", line 58, in create_animation_frames
    frame_image = PILHelper.create_scaled_image(deck, frame)
AttributeError: module 'StreamDeck.ImageHelpers.PILHelper' has no attribute 'create_scaled_image'
```

**To Reproduce**
See error above.

**StreamDeck Information**
Streamdeck v2 15 key.

**System Information**
![2021-02-19-133428_814x520_scrot](https://user-images.githubusercontent.com/32484365/108546383-0c8bc400-72b7-11eb-845a-729876bf0090.png)

streamdeck in ./.local/lib/python3.9/site-packages (0.6.3) (Pulled from pip)

**Comment by abcminiuser** [comment]
0.6.3 is quite old - can you please re-try with 0.8.3? It should be available on PIP, just `pip install --upgrade stremdeck` to grab the latest.
