### ISSUE TITLE
Companion crash when using buttons for Epiphan Pearl 

### ISSUE THREAD

**Issue by WildEdric** [abcminiuser/python-elgato-streamdeck#69]
**Describe the bug**
Created a new instance for Epiphan Pearl.  All good, and Status OK and green.  Created a new regular button, and selected Down action from list as PEARL2: Start/stop streaming.  Selected correct Channel Publisher and 'Start' action to start Pearl streaming.  Companion immediately reported a problem when button pressed, and displayed error message - see attached screen shot.
Thanks :-)
**To Reproduce**
See above - happens everytime.

**StreamDeck Information**
Stream Deck 32 button

**System Information**
MacBook 15" 2017 model. OS is High Sierra 10.13.6.  

You should also include the version(s) of the library you are using - if not using a tagged release, list the commit hash you are testing here.
Bitfocus Companion
2.0.0 (2.0.0-d8475a4-1977)
<img width="1680" alt="Screen Shot 2021-05-10 at 15 41 54" src="https://user-images.githubusercontent.com/57837265/117681243-d0774980-b1a9-11eb-86f9-1bb8408435d6.png">

**Comment by naggie** [comment]
@WildEdric I think you're reporting a bug in the wrong place. This is a repository for a python library used to interface with streamdecks. It has nothing to do with Bitfocus companion as far as I can tell, as I think companion uses a javascript library to interface with the streamdeck.

Perhaps https://github.com/bitfocus/companion is where you meant to post the bug report?

**Comment by WildEdric** [comment]
Ah, sorry - my bad.  I’ll report in the right place :-)

Thx for letting me know 

Best wishes,
Carl

Carl Walker
Wild Edric Media
m: 07779 015896
e: ***@***.***
w: wildedricmedia.com
Please connect with me on LinkedIn: www.linkedin.com/in/CarlWalker

Company Reg No. 09074633

This email and any attachments to it may be confidential and are intended solely for the use of the individual to whom it is addressed.
Any views or opinions expressed are solely those of the author and do not necessarily represent those of Wild Edric Media.
If you are not the intended recipient of this email, you must neither take any action based upon its contents, nor copy or show it to anyone.
Please contact the sender if you believe you have received this email in error.

To unsubscribe from Wild Edric Media emails in future please contact ***@***.*** to be removed from our email list.
