### ISSUE TITLE
Debian with XL - TransportError: Could not open HID device

### ISSUE THREAD

**Issue by humbled** [abcminiuser/python-elgato-streamdeck#70]
This has been working fine for a year, but after a restart yesterday I'm now getting this error. I assume due to OS unattended upgrades that have been applied. I've seen #63 and others, followed the troubleshooting steps in there, as well as making sure I followed the precursor steps too. Same error. I'm on Buster which is python3.7, but have now side installed python 3.9.5 to get the latest streamdeck (0.8.4).

```
dpkg -l | grep hid
ii  libhidapi-libusb0:amd64         0.8.0~rc1+git20140818.d17db57+dfsg-2 amd64        Multi-Platform library for communication with HID devices (libusb backend)
```

`/etc/udev/rules.d/10-streamdeck.rules:`
```
SUBSYSTEMS=="usb", ATTRS{idVendor}=="0fd9", GROUP="users", TAG+="uaccess"
SUBSYSTEM=="usb", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="0060", TAG+="uaccess"
SUBSYSTEM=="usb", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="0063", TAG+="uaccess"
SUBSYSTEM=="usb", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="006c", TAG+="uaccess"
SUBSYSTEM=="usb", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="006d", TAG+="uaccess"
```

`pip list:`
```
Package      Version
------------ -------
click        8.0.1
Flask        2.0.1
hid          1.0.4
itsdangerous 2.0.1
Jinja2       3.0.1
MarkupSafe   2.0.1
Pillow       8.2.0
pip          21.1.2
setuptools   56.0.0
streamdeck   0.8.4
Werkzeug     2.0.1
```

`groups:`
```
cdrom floppy audio dip video plugdev users netdev
```

**Comment by humbled** [comment]
Given no one else has raised or commented on this I have to assume the problem is unique to my setup. I'll setup a new box and see if I reproduce it or not.

**Comment by abcminiuser** [comment]
Oops, I've been slack on this. My only native Linux machine (my old beater laptop) finally packed it in about a month or so ago, so right now the only Linux boxes I have are my home servers, which aren't super convenient for testing as they're headless and in another room of the house. One of them runs Ubuntu 20.04 LTS so if you can repro this I might be able to troubleshoot on that.

**Comment by humbled** [comment]
@abcminiuser Thanks. Oddly it came right. I have no answer as to why that might be, except to say that I'm stoked it did. Thanks for following up anyway.
