### ISSUE TITLE
Cant install via PIP

### ISSUE THREAD

**Issue by jonneymendoza** [abcminiuser/python-elgato-streamdeck#72]
**Describe the bug**
installing steamdeck via terminal console

**To Reproduce**
pip install streandeck
ERROR: Could not find a version that satisfies the requirement streandeck
ERROR: No matching distribution found for streandeck

**StreamDeck Information**
List the model of StreamDeck(s) you are using here.

- Stream Deck XL

**System Information**
POP OS 21.04
AMD 3960x
128GB Ram
3090RTX

**Comment by dirkk0** [comment]
I think you have a typo; you wrote 'streandeck' where it should be 'streamdeck'.

**Comment by jonneymendoza** [comment]
Actually I had to type pip3

**Comment by abcminiuser** [comment]
This library is Python 3 only, so yes, `pip3` is the way to go if your system has both 2 and 3 installed. Glad you got yourself sorted!

- Dean
