### ISSUE TITLE
Support for the Stream Deck Mk.2

### ISSUE THREAD

**Issue by jakobbuis** [abcminiuser/python-elgato-streamdeck#73]
**Is your feature request related to a problem? Please describe.**
I've ordered a Stream Deck Mk.2, while using Linux (Ubuntu specifically). I'd like to use this library with it. 

**Describe the solution you'd like**
Support for using this library with the Streamdeck Mk.2

**Describe alternatives you've considered**
None

**Additional context**

1. I'm an experienced dev, but new to Python. 
2. I'm willing to help.

What I found out so far:
1. Elgato claims there are no hardware changes, atleast on a high-level: https://help.elgato.com/hc/en-us/articles/4405167312397-Elgato-Stream-Deck-What-is-the-difference-between-Stream-Deck-and-Stream-Deck-MK-2
2. Running the current lib does not detect the device. I _think_ that is because it's usb id(?) has changed. It pops up in my lsusb as:
    ```
    Bus 001 Device 044: ID 0fd9:0080 Elgato Systems GmbH Stream Deck MK.2
    ```

**Comment by jakobbuis** [comment]
I have some time to tinker with the python code over the weekend, mostly created this ticket to have a place where I can write intermediate updates, and ask for help and guidance. :) If there's another place that would be better suited, please let me know.

**Comment by asmaps** [comment]
This should also be added to the "manual installation" part on the website.
