### ISSUE TITLE
Proposal: Make readers poll timer configurable

### ISSUE THREAD

**Issue by itsjfx** [abcminiuser/python-elgato-streamdeck#76]
https://github.com/abcminiuser/python-elgato-streamdeck/blob/dc94c1718cbb01391790ba09de4977e8fcc19b8a/src/StreamDeck/Devices/StreamDeck.py#L110

Would be cool to have this poll timer configurable to aid with real-time apps.

I guess you could set it in the constructor for the base Streamdeck class and then users could set the value to what they want in a Streamdeck instance / or you could have a method to let people set it.

Also thank you for the excellent library, it's been a lot of fun building my own buttons. I found other UI projects which are based on this library to be extremely heavy whereas this one is so light and does everything... so thank you!

**Comment by abcminiuser** [comment]
I used an interval of .05s (20Hz) as I figured this would be fast enough to detect keypresses in the majority of situations.

That's probably not a bad idea; I'm annoyed that it has to use polling in the first place (ideally it would use a blocking file descriptor that's released by the kernel when a report comes in, but it's a nightmare and a half getting it working with the polled version...) but it's easy enough to make the poll time configurable.

**Comment by abcminiuser** [comment]
Implemented in 3614324348a30d6c64e281534935ae7f15df4895.
