### ISSUE TITLE
Are these non-blocking reads?

### ISSUE THREAD

**Issue by dodgyrabbit** [abcminiuser/python-elgato-streamdeck#77]
https://github.com/abcminiuser/python-elgato-streamdeck/blob/2786a795a05b441d1271e694b6b3c8e7871060b1/src/StreamDeck/Transport/Transport.py#L125

I was reading through the code and noticed that the documentation refers to blocking reads in various places. However, when the device is opened, the [non-blocking flag is set](https://github.com/abcminiuser/python-elgato-streamdeck/blob/2786a795a05b441d1271e694b6b3c8e7871060b1/src/StreamDeck/Transport/LibUSBHIDAPI.py#L183).

Is the comment wrong is or my understanding wrong?
Thanks!

**Comment by abcminiuser** [comment]
The documentation is wrong, and I'll need to fix it up; they should indeed be non-blocking (hence the polling thread and sleep in the `StreamDeck` classes. Originally I used blocking reads, however the read did not complete early on all platforms when the device went offline due disconnection or other failure, so I switched it over.

**Comment by abcminiuser** [comment]
Documentation updated in 2ab3ce9a004ca0ed719e9aba239d34ba4e885348.
