### ISSUE TITLE
Absent License of Harold.jpg

### ISSUE THREAD

**Issue by kretcheu** [abcminiuser/python-elgato-streamdeck#80]
There are no license of this image.

Would you define one? I think Harold will be happy!

**Comment by abcminiuser** [comment]
Haha, I forgot about that. I've asked Harold and he graciously agreed to license out his photo as CC0 (public domain) in exchange for extra kibble. I'll add the license to the repo.

**Comment by abcminiuser** [comment]
Fixed in 6ee63a318bb270cf895845a35abab702fb9a2702.
