### ISSUE TITLE
ProbeError when using DeviceManager().enumerate()

### ISSUE THREAD

**Issue by Charonum** [abcminiuser/python-elgato-streamdeck#84]
Hello,
I just started using this module on Windows and on my second line, I get get a ProbeError. The full error is `StreamDeck.DeviceManager.ProbeError: ('Probe failed to find any functional HID backend.', {'libusb': TransportError("No suitable LibUSB HIDAPI library found on this system. Is the 'hidapi.dll' library installed?")})`

I tried to get the devices using `DeviceManager().enumerate()` and my full code is:
```
import StreamDeck.DeviceManager as d

d.DeviceManager().enumerate()
```

Any ideas on how to fix this? Thanks

**Comment by abcminiuser** [comment]
Did you follow the installation instructions at https://python-elgato-streamdeck.readthedocs.io/en/stable/pages/backend_libusb_hidapi.html - i.e. install the HIDAPI DLL onto your system?

**Comment by Charonum** [comment]
That seemed to have flown over my head when I read the documentation, so thanks for pointing that out. I installed it, added it to PATH, and tested it in command prompt, but I still get the same error.

Thanks for your help

**Comment by Charonum** [comment]
After a lot of testing, I have fixed the problem by moving hidapi to the System32 folder.
