### ISSUE TITLE
Can I run a relative command in StreamDeck?

### ISSUE THREAD

**Issue by ArisaBonsaiTree** [abcminiuser/python-elgato-streamdeck#85]
Currently I have a script, will post below, that works perfectly when I type it as ". ./terminal"

The . is very important and needed to make sure the script goes to the proper directories.

In the StreamDeck, I have tried the command ". ./terminal.sh" and it doesn't work

I tried "gnome-terminal && . ./terminal.sh", but that doesn't work either. The gnome-terminal part works, but the second part doesn't work.

The closest I've gotten was running /home/arisa/terminal.sh, however this doesn't set the directories properly. 

Maybe I'm missing something to have ". ./terminal.sh" in the command and could be a simple mistake? 

Everything else works perfectly, so thank you for making a Linux port. 

=====================================
vim terminal.sh
#!/bin/bash
  
cd /home/arisa/VSCode/twitter_react/server
xdotool key ctrl+shift+t

cd /home/arisa/VSCode/twitter_react/client
clear

**Comment by abcminiuser** [comment]
This is just a low level StreamDeck interface library for developing applications - are you perhaps referring to the [StreamDeck UI](https://github.com/timothycrosley/streamdeck-ui) project instead, which is built on top of this library?

**Comment by ArisaBonsaiTree** [comment]
Yeah, I meant to refer to StreamDeck UI.

I've actually resolved this "issue/question" yesterday. In case anyone wants to know, how would you type ". ./nameOfScript"

You put the following in Command: "xdotool type ". ./nameOfScript". This should type it out for you.

In Press Keys: "delay+ENTER" This should press enter for you after a 0.5 second delay.

I wrote it here, since I know how annoying it is when someone goes "nm I solved it."

Simple, but you never know who may happen to search for this question in the wrong repository... 

Sorry for writing my issue/question on the wrong repository. 

Hopefully as I play with it more, I'll find better shortcuts. Thank you for making a Linux port and have a good day.
