### ISSUE TITLE
How do you reset the stream deck if the script crashed?

### ISSUE THREAD

**Issue by philipperemy** [abcminiuser/python-elgato-streamdeck#87]
Now what I do is unplugging the stream deck to reset it.

Otherwise the HID API is stuck because the Stream Deck is used by a former script.

Thanks

**Comment by philipperemy** [comment]
It's not a bug it's just a question

**Comment by dodgyrabbit** [comment]
Generally you will need to find the running process (your previous script) and kill it. Depending on your operating system the steps can vary. On Linux the easiest is to use `htop` or `ps -aux`. Once the original process is killed, you can start a new process that will initialize the streamdeck.

**Comment by philipperemy** [comment]
So the problem does not happen with MacOS. Its just linux. It's probably a problem with HID USB API.
