### ISSUE TITLE
StreamdeckOriginalV2 Firmware Reset | (Currently streamdeck black buttons)

### ISSUE THREAD

**Issue by EngineerIT14** [abcminiuser/python-elgato-streamdeck#92]
Hello, I would like to have an option to reset my firmware to the default one:

**Is your feature request related to a problem? Please describe.**
Yes, it is related to a big problem that came with the FW  '1.02.007' | Streamdeck version 2, I already discussed this on Reddit (https://www.reddit.com/r/elgato/comments/t7soxm/stream_deck_displaying_black_buttons/) but the main issue is that seems that this firmware version affects the LCD buttons never turn ON again (they are black), the stream deck is working but is not displaying anything so I want to use this repo to reset the firmware or maybe a script to fix this issue.

**Describe the solution you'd like**

A script to reset the firmware or reinstall the current firmware to install it properly and see if that fixes the black buttons problem

**Describe alternatives you've considered**
Reinstalling software, plug and unplug to different USB ports and nothing works. Streamdeck is still with black buttons El Gato support only gives the option to replace the device but this option is not viable for the people that are not in the US.

I´m waiting for a new firmware update but I have been waiting for months and there is no new firmware update yet...

**Comment by Devnuel14** [comment]
There are a lot of people with this firmware problem (https://twitter.com/strawbelliott/status/1475894755624034304), this solution will give them the opportunity to have the lcd buttons working again..

**Comment by Devnuel14** [comment]
@abcminiuser or do you think there is a script in this repo that can help me with this problem? I have been looking for a fix for months but ELGATO wants to clean their hands and replace it with a new device (that sucks because I need to send them from other country and it will be expensive)

**Comment by Julusian** [comment]
I feel like this will be very difficult to achieve.
To start with, someone will need to find a copy of the firmware. And then figure out how to transfer that to a streamdeck without corrupting it and potentially bricking the streamdeck in the process.

I considered trying to do this in the node library at one point, but decided it was too difficult to do

**Comment by Devnuel14** [comment]
@Julusian  Or maybe to remove the current firmware so the official software detects that it does not have the most recent firmware and the enable you the "update firmware" button, I know it is difficult but it would be a very good feature for any person that struggles with this problem

**Comment by Julusian** [comment]
It is highly unlikely to be possible to remove the firmware. To do so will likely leave the device in a unfixably broken state.
Even restoring/reseting the firmware to the original is likely not possible as it probably wrote over itself in the update process.

Pretty much everything that can be done to the streamdeck through libraries like this is done by doing stuff in the elgato software and analysing what went over usb. So it is only possible to provide features that elgato have available in their software

**Comment by Devnuel14** [comment]
@Julusian  So your recommendation for my case would be to wait for the next firmware update (It has been since December since this problem and no update yet) or buy a new stream deck, right?

**Comment by Julusian** [comment]
Unfortonately yes, I think those are your only options

**Comment by abcminiuser** [comment]
I apparently completely missed this discussion last year, sorry! I haven't been keeping close tabs on Github outside of email notifications, and didn't notice this one somehow.

Sounds like it was a Corsair firmware problem that I imagine has since been resolved.

Reverse engineering their firmware is always possible with Ghidra, but frankly not worth it. I highly doubt they're bothering to sign their binaries but if they are, fixing issues in their code won't help if there's no way to sign it into a format the device would accept.
