### ISSUE TITLE
StreamDeck.Transport.Transport.TransportError on macOS Monterey v12.4.

### ISSUE THREAD

**Issue by YuenEsc** [abcminiuser/python-elgato-streamdeck#94]
It's not working for me on macOS Monterey v12.4.
This is the error I'm getting

Found 1 Stream Deck(s).
```
Traceback (most recent call last):
  File "/Users/yuensteven/Developer/python-elgato-streamdeck/src/example_deckinfo.py", line 52, in <module>
    deck.open()
  File "/Users/yuensteven/Developer/python-elgato-streamdeck/src/StreamDeck/Devices/StreamDeck.py", line 155, in open
    self.device.open()
  File "/Users/yuensteven/Developer/python-elgato-streamdeck/src/StreamDeck/Transport/LibUSBHIDAPI.py", line 352, in open
    self.device_handle = self.hidapi.open_device(self.device_info['path'])
  File "/Users/yuensteven/Developer/python-elgato-streamdeck/src/StreamDeck/Transport/LibUSBHIDAPI.py", line 181, in open_device
    raise TransportError("Could not open HID device.")
StreamDeck.Transport.Transport.TransportError: Could not open HID device.
```

**Comment by abcminiuser** [comment]
Sorry for the long delay - I've had a newborn in the last few months which has left me with little free time.

This looks like a permissions error more than anything, does your user account have access to the raw HID device? You can temporarily run the example scripts with `sudo` to check if it's permissions related or not.

**Comment by fharper** [comment]
I have the same issue, but I don't think it's permission related as I can list, and open the StreamDeck without root using [hidapitester](https://github.com/todbot/hidapitester)

**Comment by fharper** [comment]
Also, congrats on the new baby @abcminiuser 🎉

**Comment by Mariam-Bassem** [comment]
I have the same issue also on macOS Monterey 12.5.1. both rebooting and running the script as a `sudo` doesn't seems to help

Any suggestion?

**Comment by abcminiuser** [comment]
I've just tried this on a native M1 machine, and it was able to use my original StreamDeck with no issues (and no `sudo`). MacOS Monterey 12.6.1.

Given your update, it sounds like the official software had exclusive access to the device, so I'll close this issue for now unless someone's still having troubles with the latest HEAD.

**Comment by KazukiOmata** [comment]
I have same problem. 
Mac OS M1 Max and Sonoma 14.3.1
Does `hidapi` work if I install it with arm64 brew?
Any suggestion?

**Comment by abcminiuser** [comment]
Hidapi should work if installed via Homebrew.
