### ISSUE TITLE
New variant of mini

### ISSUE THREAD

**Issue by Julusian** [abcminiuser/python-elgato-streamdeck#95]
I have been talking with a user of an application based around https://github.com/julusian/node-elgato-stream-deck, and they appear to have a new variant of the mini.
Model number 20GAI9902, productId 0x0090.

I haven't yet been able to verify the protocol or get anything functioning (no direct access is making for a really slow iteration time).
I shall try and report back once I have made progress.

If you get bug reports from users that their new mini is not working, this new revision is likely to be the cause

**Comment by Julusian** [comment]
An update, I believe to have a working implementation of this now.
The only difference to the old mini is the productId, and the call 
https://github.com/abcminiuser/python-elgato-streamdeck/blob/3fd78df3f8d89a3e37f4f146dc92b91bb9842037/src/StreamDeck/Devices/StreamDeckMini.py#L108
needs to have the second parameter as `32`

**Comment by Julusian** [comment]
@RocketSEA that and mapping the new productId

**Comment by abcminiuser** [comment]
Sorry for the long radio silence; I've had a newborn in the last few months, and haven't had much time for other projects :).

This should be resolved in 8fbd0f675bdeb8d8ad592da1dae8d10cc584075a onwards; can you please test the latest master branch and confirm it is working so I can tag and release?
