### ISSUE TITLE
New revision of the XL

### ISSUE THREAD

**Issue by Julusian** [abcminiuser/python-elgato-streamdeck#96]
There appears to be a new revision of the XL with a new usb product id (source: https://github.com/bitfocus/companion/issues/2113)

I haven't begun on checking for protocol changes, I shall report back once I have more details.

**Comment by swedishmike** [comment]
I just added a PR for this, just getting the code to be recognised at least. (https://github.com/abcminiuser/python-elgato-streamdeck/pull/100)

**Comment by Julusian** [comment]
I've forgotten to report back, but based on user feedback it appears that it is simply an id change and nothing in the protocol.

**Comment by swedishmike** [comment]
I'm new to the Streamdeck but just this addition seems to make it work via the Streamdeck UI without any issues. It _looks_ like my PR should be enough.

**Comment by abcminiuser** [comment]
Fixed in 0.9.3. Thanks all!
