### ISSUE TITLE
Create new release for downstream?

### ISSUE THREAD

**Issue by RocketSEA** [abcminiuser/python-elgato-streamdeck#97]
Hello,

I noticed the most recent release is from April. Are there any plans for a new tagged release soon? Some downstream packages still do not support the new Mini since the changes haven't been published with a tag.

Thank you!

**Comment by abcminiuser** [comment]
Sure, I was hoping someone would confirm that HEAD worked with it first, but I guess someone will open a new issue here if it fails with the new hardware.

Tagged 0,9.2 and released to PyPi.
